version: '3.1'

volumes:
  minio-data:
    driver: local

services:
  app:
    image: 'telros:latest'
    build:
      context: .
    container_name: userInfoApplication
    ports:
      - 8080:8080
    depends_on:
      - db
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/telros
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    env_file:
      - .env


  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio
    env_file:
      - .env

  db:
    image: 'postgres:14.5-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=telros
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "54320:5432"



